CREATE DATABASE CARFORUM;

USE CARFORUM;
DROP TABLE USERACCOUNT;
CREATE TABLE USERACCOUNT(
USERID INT AUTO_INCREMENT PRIMARY KEY,
FName VARCHAR(30) NOT NULL,
LName VARCHAR(30) NOT NULL,
PASSWORD VARCHAR(40) NOT NULL,
CARINTERESTS VARCHAR(80) NOT NULL,
FRIENDLIST INT(1) NOT NULL,
DESCRIPTION VARCHAR(500) NOT NULL,
PREFERENCES VARCHAR(400) NOT NULL,
IMAGEID INT(10));

ALTER TABLE USERACCOUNT ADD CONSTRAINT IMAGE_FK FOREIGN KEY (IMAGEID) REFERENCES IMAGE(IMAGEID);


DROP TABLE EVENT;
CREATE TABLE EVENT (
EVENTID INT AUTO_INCREMENT PRIMARY KEY,
EVENTNAME VARCHAR(30) NOT NULL,
USERID INT (225),
EVENTDESCRIPTION VARCHAR(30) NOT NULL,
EVENTLOCATION VARCHAR(60) NOT NULL,
DateTimeStart DATETIME);

ALTER TABLE EVENT ADD CONSTRAINT USERACCOUNT_FK FOREIGN KEY (USERID) REFERENCES USERACCOUNT(USERID);


create table IMAGE (
IMAGEID int(10) AUTO_INCREMENT PRIMARY KEY,
IMAGE BLOB NOT NULL,
USERID INT(225);
--ALTER TABLE IMAGE ADD CONSTRAINT USERACCOUNT_FK FOREIGN KEY (USERID) REFERENCES USERACCOUNT(USERID);


CREATE TABLE PAGE (
PAGEID INT AUTO_INCREMENT PRIMARY KEY,
PAGENAME VARCHAR(30) NOT NULL,
DESCRIPTION VARCHAR(500) NOT NULL,
LOCATION VARCHAR(60) NOT NULL,
USERID INT (225),
IMAGEID INT (10));


ALTER TABLE PAGE ADD CONSTRAINT FK_IMAGE FOREIGN KEY (IMAGEID) REFERENCES IMAGE(IMAGEID);
ALTER TABLE PAGE ADD CONSTRAINT FK_USERACCOUNT FOREIGN KEY (USERID) REFERENCES USERACCOUNT(USERID);

CREATE TABLE CARS (
CARID INT AUTO_INCREMENT PRIMARY KEY,
TAGS VARCHAR(30) NOT NULL,
CARNAME VARCHAR(500) NOT NULL,
CARDESCRIPTION VARCHAR(500) NOT NULL,
IMAGEID INT (10));


--ALTER TABLE CARS ADD CONSTRAINT IMAGE_FK FOREIGN KEY (IMAGEID) REFERENCES IMAGE(IMAGEID);

CREATE TABLE MANUFACTURER (
MANUID INT AUTO_INCREMENT PRIMARY KEY,
MANUFACTURERNAME VARCHAR(500) NOT NULL,
TAGS VARCHAR(30) NOT NULL,
MANUFACTURERDESCRIPTION VARCHAR(500) NOT NULL,
IMAGEID INT (10));
--ALTER TABLE MANUFACTURER ADD CONSTRAINT IMAGE_FK FOREIGN KEY (IMAGEID) REFERENCES IMAGE(IMAGEID);

ALTER TABLE USERACCOUNT ADD CONSTRAINT IMAGE_FK FOREIGN KEY (IMAGEID) REFERENCES IMAGE(IMAGEID);
ALTER TABLE EVENT ADD CONSTRAINT USERACCOUNT_FK FOREIGN KEY (USERID) REFERENCES USERACCOUNT(USERID);
--ALTER TABLE IMAGE ADD CONSTRAINT USERACCOUNT_FK FOREIGN KEY (USERID) REFERENCES USERACCOUNT(USERID);
ALTER TABLE PAGE ADD CONSTRAINT FK_IMAGE FOREIGN KEY (IMAGEID) REFERENCES IMAGE(IMAGEID);
ALTER TABLE PAGE ADD CONSTRAINT FK_USERACCOUNT FOREIGN KEY (USERID) REFERENCES USERACCOUNT(USERID);
--ALTER TABLE CARS ADD CONSTRAINT IMAGE_FK FOREIGN KEY (IMAGEID) REFERENCES IMAGE(IMAGEID);
--ALTER TABLE MANUFACTURER ADD CONSTRAINT IMAGE_FK FOREIGN KEY (IMAGEID) REFERENCES IMAGE(IMAGEID);
